[package]
name = "shielded_mol_py"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "shielded_mol_py"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.27.0"
shielded_molecules = { path = "../" }